### ISSUE TITLE
osc.NewMessage missing provokes errors

### ISSUE THREAD

**Issue by vrx** [briansorahan/sc#6]
constructor osc.NewMessage has been deleted from package osc and scgolang does not compile anymore...

go get github.com/scgolang/sc
# github.com/scgolang/sc
src/github.com/scgolang/sc/buffer.go:76: gen.WriteInt32 undefined (type *osc.Message has no field or method WriteInt32)
src/github.com/scgolang/sc/buffer.go:79: gen.WriteString undefined (type *osc.Message has no field or method WriteString)
src/github.com/scgolang/sc/buffer.go:82: gen.WriteInt32 undefined (type *osc.Message has no field or method WriteInt32)
src/github.com/scgolang/sc/buffer.go:86: gen.WriteFloat32 undefined (type *osc.Message has no field or method WriteFloat32)
src/github.com/scgolang/sc/buffer.go:104: done.CountArguments undefined (type *osc.Message has no field or method CountArguments)
src/github.com/scgolang/sc/buffer.go:107: done.ReadString undefined (type *osc.Message has no field or method ReadString)
src/github.com/scgolang/sc/buffer.go:116: done.ReadInt32 undefined (type *osc.Message has no field or method ReadInt32)
src/github.com/scgolang/sc/client.go:157: cannot use oscConn (type *osc.UDPConn) as type osc.Conn in assignment:
	*osc.UDPConn does not implement osc.Conn (missing Read method)
src/github.com/scgolang/sc/client.go:221: msg.WriteBlob undefined (type *osc.Message has no field or method WriteBlob)
src/github.com/scgolang/sc/client.go:238: done.CountArguments undefined (type *osc.Message has no field or method CountArguments)
src/github.com/scgolang/sc/client.go:238: too many errors

**Comment by briansorahan** [comment]
@vrx I rewrote large parts of the osc package and will fix this today

**Comment by briansorahan** [comment]
@vrx Let me know if you see any other issues!
